- hosts: master
  become: no
  gather_facts: false
  tasks:
    - name: copy helm values
      copy:
        src: ~/dev/tools/ansible_k8s/conf/nginx-ingress-values.yaml
        dest: ~/nginx-ingress-values.yaml
    - name: copy helm values
      copy:
        src: ~/dev/tools/ansible_k8s/conf/cert-manager-values.yaml
        dest: ~/cert-manager-values.yaml
    - name: set up nginx ingress
      shell: helm install --name nginx-ingress --namespace nginx-ingress stable/nginx-ingress -f ~/nginx-ingress-values.yaml
    - name: add cert man namespace
      shell: kubectl create namespace cert-manager
    - name: add crds
      shell: kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
    - name: add jetstack repo
      shell: helm repo add jetstack https://charts.jetstack.io && helm repo update
    - name: install cert-manager
      shell: helm install --name cert-manager --namespace cert-manager --version v0.11.0 -f ~/cert-manager-values.yaml jetstack/cert-manager
    - name: copy cluster-issuer
      copy:
        src: ~/tools/kube-cluster/conf/cluster-issuer.yaml
        dest: ~/cluster-issuer.yaml
    - name: add le prod clusterissuer
      shell: kubectl apply -f ~/cluster-issuer.yaml
